baseURL = 'https://ahobobo.github.io/table-taker/'
languageCode = 'en-us'
title = 'Table Takers'
theme = "hugo-dusk"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        useEmbedded = "fallback"


[params.meta]
  keywords = "blog, ttrpg, creative"
  description = "Personal blog."
[params]
  mainSections = ['posts', 'blog']
  github = 'https://github.com/ahobobo/table-taker'

[taxonomies]
  campaign = 'campaigns'
  character = 'characters'
  game = 'games'
  session = 'sessions'
  tag = 'tags'

[menus]
    [[menus.main]]
        name = 'Blog'
        pageRef = '/blog/'
        weight = 20